### ISSUE TITLE
안녕하세요 예제 ch12 실행시키려는데 문제가 있는거 같습니다. 

### ISSUE THREAD

**Issue by yangbongsoo** [holyeye/jpabook#1]
안녕하세요 ch12의 jpabook.jpashop.repository.custom 패키지의 OrderRepositoryImpl 클래스에 
QOrder, QMember 클래스에 에러가 있어서 보니까 jpabook.jpashop.domain에 QOrder, QMember클래스가 존재하지 않아 import 에러가 발생했습니다. 

책의 내용(p430)을 보니까 mvn compile을 입력하면 자동으로 Q가붙은 엔티티클래스가 생성된다는 말씀인가요?

즉 예제를 다운받고 제가 mvn compile을 실행시켜야 Q~관련 파일이 생성되고 그거를 자바소스쪽에 복붙해야 된다는 말씀인가요??

**Comment by holyeye** [comment]
네 말씀하신대로 mvn compile하면 Q클라스파일이 자동으로 생성됩니다.
그리고 코드를 복붙하는 것이 아니라 클래스가 생성된 경로를 소스코드 경로로 ide에서 잡아주시면 되요.
참고로 요즘 ide들은 메이즌과 연동이 잘 되어 있어서 자동으로 소스코드 경로로 잡아줍니다.

**Comment by yangbongsoo** [comment]
답변 감사합니다 !!

**Comment by highdali** [comment]
ch2 실행시키려는데 

```
INFO: HHH000397: Using ASTQueryTranslatorFactory
5월 11, 2017 2:01:25 오후 org.hibernate.hql.internal.ast.ErrorCounter reportError
ERROR: line 1:15: unexpected token: Member
5월 11, 2017 2:01:25 오후 org.hibernate.hql.internal.ast.ErrorCounter reportError
ERROR: line 1:15: unexpected token: Member
line 1:15: unexpected token: Member
	at org.hibernate.hql.internal.antlr.HqlBaseParser.fromRange(HqlBaseParser.java:1516)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.fromClause(HqlBaseParser.java:1340)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.selectFrom(HqlBaseParser.java:1060)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.queryRule(HqlBaseParser.java:745)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.selectStatement(HqlBaseParser.java:316)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.statement(HqlBaseParser.java:198)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:283)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:186)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:541)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:650)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:674)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at Main.logic(Main.java:55)
	at Main.main(Main.java:23)

java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: Member near line 1, column 15 [select m from Member m]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:131)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:658)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:674)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at Main.logic(Main.java:55)
	at Main.main(Main.java:23)
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: Member near line 1, column 15 [select m from Member m]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorCounter.throwQueryException(ErrorCounter.java:91)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:292)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:186)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:541)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:650)
	... 4 more
```

그래서

```java
em.createQuery("select m from Member m", Member.class).getResultList();
```

를

```java
List<Member> members = em.createNativeQuery("select * from Member", Member.class).getResultList();
```

로 바꾸어주니 되요.

**Comment by highdali** [comment]
ch2 실행하는데 디폴트패키지에 있으면 `createQuery` 부분에서 에러가 발생하네요..ㅎ;;
